jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Bicep linter
        run: az bicep build --file ./main.bicep

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'

    steps:
      - uses: actions/checkout@v2
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Deploy Dev Environment
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.Webhook_URL }}
        run: |
          az deployment group create \
            --resource-group ${{ env.RESOURCE_GROUP_DEV }} \
            --template-file ./main.bicep \
            --parameters @./parameters/dev.bicepparam \
            --parameters slackWebhookUrl=$SLACK_WEBHOOK_URL \
                         logicAppName="bestbank-logicapp-dev" \
                         location="East US"

  deploy-uat:
    if: (github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'main') || github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [build, deploy-dev]
    environment:
      name: 'UAT'

    steps:
      - uses: actions/checkout@v2
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Deploy UAT Environment
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.Webhook_URL }}
        run: |
          az deployment group create \
            --resource-group ${{ env.RESOURCE_GROUP_UAT }} \
            --template-file ./main.bicep \
            --parameters @./parameters/uat.bicepparam \
            --parameters slackWebhookUrl=$SLACK_WEBHOOK_URL \
                         logicAppName="bestbank-logicapp-uat" \
                         location="East US"
