name: ie-bank-infra

on:
  workflow_dispatch:
  push:
      paths-ignore:
        - 'scripts/**'
  pull_request:
    branches: ["main"]

env:
  RESOURCE_GROUP_DEV: BCSAI2024-DEVOPS-STUDENTS-A-DEV
  RESOURCE_GROUP_UAT: BCSAI2024-DEVOPS-STUDENTS-A-UAT
  SUBSCRIPTION_ID_DEV: e0b9cada-61bc-4b5a-bd7a-52c606726b3b
  SUBSCRIPTION_ID_UAT: e0b9cada-61bc-4b5a-bd7a-52c606726b3b
  USER_ALIAS: bestbank

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Validate and build Bicep templates
      - name: Run Bicep build
        run: az bicep build --file ./main.bicep

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Log into Azure
      - name: Log into Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy to DEV
      - name: Deploy Bicep to DEV
        uses: azure/arm-deploy@v2
        with:
          subscriptionId: ${{ env.SUBSCRIPTION_ID_DEV }}
          resourceGroupName: ${{ env.RESOURCE_GROUP_DEV }}
          template: ./main.bicep
          parameters: |
            containerRegistryName=${{ secrets.CONTAINER_REGISTRY_NAME }}
            keyVaultName=${{ secrets.KEY_VAULT_NAME }}
            appServicePlanName=${{ secrets.APP_SERVICE_PLAN_NAME }}
            appServiceBackendName=${{ secrets.APP_SERVICE_BACKEND_NAME }}
            backendDockerImageName=${{ secrets.DOCKER_IMAGE_NAME }}
            backendDockerImageVersion=latest
            staticWebAppName=${{ secrets.STATIC_WEB_APP_NAME }}
            staticWebAppRepositoryToken=${{ secrets.GITHUB_TOKEN }}
            staticWebAppRepositoryUrl=${{ secrets.STATIC_WEB_APP_REPOSITORY_URL }}
            postgreSQLServerName=${{ secrets.DBHOST }}
            postgreSQLAdminUsername=${{ secrets.DBUSER }}
            postgreSQLAdminPassword=${{ secrets.DBPASS }}
            postgreSQLDatabaseName=${{ secrets.DBNAME }}
          deploymentName: ${{ env.USER_ALIAS }}-dev

  deploy-uat:
    if: (github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'main') || github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [build, deploy-dev]
    environment:
      name: 'UAT'
    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Log into Azure
      - name: Log into Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy to UAT
      - name: Deploy Bicep to UAT
        uses: azure/arm-deploy@v2
        with:
          subscriptionId: ${{ env.SUBSCRIPTION_ID_UAT }}
          resourceGroupName: ${{ env.RESOURCE_GROUP_UAT }}
          template: ./main.bicep
          parameters: |
            containerRegistryName=${{ secrets.CONTAINER_REGISTRY_NAME }}
            keyVaultName=${{ secrets.KEY_VAULT_NAME }}
            appServicePlanName=${{ secrets.APP_SERVICE_PLAN_NAME }}
            appServiceBackendName=${{ secrets.APP_SERVICE_BACKEND_NAME }}
            backendDockerImageName=${{ secrets.DOCKER_IMAGE_NAME }}
            backendDockerImageVersion=latest
            staticWebAppName=${{ secrets.STATIC_WEB_APP_NAME }}
            staticWebAppRepositoryToken=${{ secrets.GITHUB_TOKEN }}
            staticWebAppRepositoryUrl=${{ secrets.STATIC_WEB_APP_REPOSITORY_URL }}
            postgreSQLServerName=${{ secrets.DBHOST }}
            postgreSQLAdminUsername=${{ secrets.DBUSER }}
            postgreSQLAdminPassword=${{ secrets.DBPASS }}
            postgreSQLDatabaseName=${{ secrets.DBNAME }}
          deploymentName: ${{ env.USER_ALIAS }}-uat
