jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'

    steps:
      - uses: actions/checkout@v2
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Deploy Dev Environment
        uses: azure/arm-deploy@v2
        with:
          scope: resourcegroup
          subscriptionId: ${{ env.SUBSCRIPTION_ID_DEV }}
          resourceGroupName: ${{ env.RESOURCE_GROUP_DEV }}
          template: ./main.bicep
          parameters: |
            slackWebhookUrl=${{ secrets.Webhook_URL }}
            logicAppName=bestbank-logicapp-dev
          deploymentName: ${{ env.USER_ALIAS }}-dev

  deploy-uat:
    runs-on: ubuntu-latest
    needs: [build, deploy-dev]
    environment:
      name: 'UAT'

    steps:
      - uses: actions/checkout@v2
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Deploy UAT Environment
        uses: azure/arm-deploy@v2
        with:
          scope: resourcegroup
          subscriptionId: ${{ env.SUBSCRIPTION_ID_DEV }}
          resourceGroupName: ${{ env.RESOURCE_GROUP_UAT }}
          template: ./main.bicep
          parameters: |
            slackWebhookUrl=${{ secrets.Webhook_URL }}
            logicAppName=bestbank-logicapp-uat
          deploymentName: ${{ env.USER_ALIAS }}-uat
