name: ie-bank-infra

on:
  workflow_dispatch:
  push:
      paths-ignore:
        - 'scripts/**'
  pull_request:
    branches: [ "main" ]

env:
  RESOURCE_GROUP_DEV: BCSAI2024-DEVOPS-STUDENTS-A-DEV
  RESOURCE_GROUP_UAT: BCSAI2024-DEVOPS-STUDENTS-A-UAT
  RESOURCE_GROUP_PROD: BCSAI2024-DEVOPS-STUDENTS-A-PROD
  SUBSCRIPTION_ID_DEV: e0b9cada-61bc-4b5a-bd7a-52c606726b3b
  USER_ALIAS: bestbank

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Bicep linter
        run: az bicep build --file ./main.bicep 

  bicep-unit-tests:
    name: 'Bicep Unit Tests'
    runs-on: ubuntu-latest
    needs: build
      
    steps:
      - name: Checkout
        uses: actions/checkout@v3 
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
      - name: Bicep Lint
        uses: Azure/cli@v1
        with:
          inlineScript: az bicep build --file main.bicep
      
      - name: Bicep Validate
        uses: Azure/cli@v1
        with:
          inlineScript: |
            az deployment sub validate \
            --name validate-${{ github.run_id }} \
            --template-file main.bicep \
            --location $LOCATION 
      
      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with: 
          framework: bicep
          output-file-path: results.sarif
      
      - name: Upload SARIF file
        if: success() || failure()
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
          category: checkov

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'

    steps:
      - uses: actions/checkout@v2
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      # Run ARM template deployment with parameters
      - name: deploy
        uses: azure/arm-deploy@v2
        with:
          subscriptionId: ${{ env.SUBSCRIPTION_ID_DEV }}
          resourceGroupName: ${{ env.RESOURCE_GROUP_DEV }}
          template: ./main.bicep
          parameters: ./parameters/dev.bicepparam adminUsername=${{ secrets.DEFAULT_ADMIN_USERNAME }} adminPassword=${{ secrets.DEFAULT_ADMIN_PASS }}
          

          deploymentName: ${{ env.USER_ALIAS }}-dev

  deploy-uat:
    if: (github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'main') || github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [build, deploy-dev]
    environment:
      name: 'UAT'

    steps:
      - uses: actions/checkout@v2
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Run ARM template deployment with parameters
      - name: deploy
        uses: azure/arm-deploy@v2
        with:
          subscriptionId: ${{ env.SUBSCRIPTION_ID_DEV }}
          resourceGroupName: ${{ env.RESOURCE_GROUP_UAT }}
          template: ./main.bicep
          parameters: ./parameters/uat.bicepparam adminUsername=${{ secrets.DEFAULT_ADMIN_USERNAME }} adminPassword=${{ secrets.DEFAULT_ADMIN_PASS }}
          #added the secrets for uat 
            
          deploymentName: ${{ env.USER_ALIAS }}-uat