name: ie-bank-infra

on:
  workflow_dispatch:
  push:
      paths-ignore:
        - 'scripts/**'
  pull_request:
    branches: [ "main" ]

env:
  RESOURCE_GROUP_DEV: BCSAI2024-DEVOPS-STUDENTS-A-DEV
  RESOURCE_GROUP_UAT: BCSAI2024-DEVOPS-STUDENTS-A-UAT
  RESOURCE_GROUP_PROD: BCSAI2024-DEVOPS-STUDENTS-A-PROD
  SUBSCRIPTION_ID_DEV: e0b9cada-61bc-4b5a-bd7a-52c606726b3b
  USER_ALIAS: bestbank

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Bicep linter
        run: az bicep build --file ./main.bicep 
          # echo "Linting all Bicep files in the modules folder..."
          # for file in $(find ./modules -name "*.bicep"); do
          #   echo "Linting $file..."
          #   az bicep build --file $file
          # done
  unit-test:
    name: Unit Testing for Key Vault Module
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Simulate Deployment with What-If
        run: |
                echo "Running What-If for Key Vault module..."
                az deployment group what-if \
                  --name KeyVaultUnitTest \
                  --resource-group ${{ env.RESOURCE_GROUP_DEV }} \
                  --template-file ./modules/keyVault.bicep \
                  --parameters name="test-keyvault" location="eastus" enableSoftDelete=false enableRbacAuthorization=true

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'

    steps:
      - uses: actions/checkout@v2
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      # Run ARM template deployment with parameters
      - name: deploy
        uses: azure/arm-deploy@v2
        with:
          subscriptionId: ${{ env.SUBSCRIPTION_ID_DEV }}
          resourceGroupName: ${{ env.RESOURCE_GROUP_DEV }}
          template: ./main.bicep
          parameters: ./parameters/dev.bicepparam adminUsername=${{ secrets.DEFAULT_ADMIN_USERNAME }} adminPassword=${{ secrets.DEFAULT_ADMIN_PASS }}
          

          deploymentName: ${{ env.USER_ALIAS }}-dev

  deploy-uat:
    if: (github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'main') || github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [build, deploy-dev]
    environment:
      name: 'UAT'

    steps:
      - uses: actions/checkout@v2
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Run ARM template deployment with parameters
      - name: deploy
        uses: azure/arm-deploy@v2
        with:
          subscriptionId: ${{ env.SUBSCRIPTION_ID_DEV }}
          resourceGroupName: ${{ env.RESOURCE_GROUP_UAT }}
          template: ./main.bicep
          parameters: ./parameters/uat.bicepparam adminUsername=${{ secrets.DEFAULT_ADMIN_USERNAME }} adminPassword=${{ secrets.DEFAULT_ADMIN_PASS }}
          #added the secrets for uat 
            
          deploymentName: ${{ env.USER_ALIAS }}-uat