name: Test Key Vault Configuration

on:
  workflow_dispatch:

env:
  RESOURCE_GROUP_DEV: BCSAI2024-DEVOPS-STUDENTS-A-DEV
  RESOURCE_GROUP_UAT: BCSAI2024-DEVOPS-STUDENTS-A-UAT
  SUBSCRIPTION_ID_DEV: e0b9cada-61bc-4b5a-bd7a-52c606726b3b
  SUBSCRIPTION_ID_UAT: e0b9cada-61bc-4b5a-bd7a-52c606726b3b # Replace with the correct ID if different
  USER_ALIAS: bestbank

jobs:
  test-keyvault:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Run Bicep Linter
        run: az bicep build --file modules/key-vault.bicep 

      - name: Install Azure CLI Extensions
        run: |
          az extension add --name keyvault
          az extension add --name resource-graph

      - name: Test Key Vault in Dev Environment
        run: |
          echo "Testing Key Vault configuration in DEV environment"
          az keyvault show --name "BestBank-KV-dev" --resource-group ${{ env.RESOURCE_GROUP_DEV }} --subscription ${{ env.SUBSCRIPTION_ID_DEV }} > kv-config-dev.json

          # Validate parameters
          jq 'select(.properties.enableRbacAuthorization == true)' kv-config-dev.json
          jq 'select(.properties.enableSoftDelete == false)' kv-config-dev.json

          # Validate Role Assignments
          az role assignment list --scope $(jq -r '.id' kv-config-dev.json) --query '[].roleDefinitionName' -o tsv | grep "Key Vault Secrets User"

      - name: Test Key Vault in UAT Environment
        run: |
          echo "Testing Key Vault configuration in UAT environment"
          az keyvault show --name "BestBank-KV-uat" --resource-group ${{ env.RESOURCE_GROUP_UAT }} --subscription ${{ env.SUBSCRIPTION_ID_UAT }} > kv-config-uat.json

          # Validate parameters
          jq 'select(.properties.enableRbacAuthorization == true)' kv-config-uat.json
          jq 'select(.properties.enableSoftDelete == false)' kv-config-uat.json

          # Validate Role Assignments
          az role assignment list --scope $(jq -r '.id' kv-config-uat.json) --query '[].roleDefinitionName' -o tsv | grep "Key Vault Secrets User"
